# Generated by Django 3.2.3 on 2021-12-21 13:51

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail_photo_gallery.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('gallery', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('collection', wagtail_photo_gallery.blocks.CollectionChooserBlock())]))], blank=True),
        ),
    ]
