# Generated by Django 4.2 on 2024-10-20 11:14

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail_photo_gallery.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('gallery', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('collection', wagtail_photo_gallery.blocks.CollectionChooserBlock()), ('ascending', wagtail.blocks.BooleanBlock(required=False)), ('grouping', wagtail.blocks.ChoiceBlock(choices=[(None, 'Ungrouped'), ('year', 'Year'), ('day', 'Day')], required=False))]))], blank=True),
        ),
    ]
