# Generated by Django 4.0 on 2024-10-19 06:24

from django.db import migrations, models
import django.db.models.deletion
import wagtail.models.collections


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtail_photo_gallery', '0002_alter_album_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='collection',
            field=models.ForeignKey(default=wagtail.models.collections.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.collection'),
        ),
    ]
