# Generated by Django 4.2 on 2024-10-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_photo_gallery', '0004_album_date_album_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
