# Generated by Django 4.2 on 2024-10-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_photo_gallery', '0005_alter_album_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
