# Generated by Django 4.2 on 2024-10-28 17:42

from django.db import migrations
import imagekit.models.fields
import wagtail_photo_gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_photo_gallery', '0006_alter_album_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=wagtail_photo_gallery.models.image_upload_to),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='thumb',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=wagtail_photo_gallery.models.thumb_upload_to),
        ),
    ]
